services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: type_recorder_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/type_recorder_development
      RAILS_ENV: development
    volumes:
      - ./backend:/app
      - /app/vendor/bundle
    command: ["sh", "-c", "bundle install && sleep 5 && bundle exec rake db:create db:migrate db:seed && rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data: